#! /usr/bin/env python
import subprocess
import memory_profiler as mp
import sys

if len(sys.argv) < 2:
    print("""Memory usage monitoring
          Usage: %s <command> <argument> ... <argument>

          Output results in a file called "profile.dat" in the current directory.
          This file contains the process memory consumption, in Mb (one value per
          line). Memory is sampled twice each second."""
          % sys.argv[0]
          )
    sys.exit(1)

p = subprocess.Popen(sys.argv[1:])
mu = mp.memory_usage(proc=p, interval=0.5)
with open("profile.dat", "w") as f:
    for m in mu:
        f.write(str(m) + "\n")
